### ISSUE TITLE
error: "numeric field did not have utf-8 text

### ISSUE THREAD

**Issue by bobdivx** [ALikhachev/ha-backup-s3-uploader#1]
hello I deployed in my kubernetes cluster, the job worked once and now I get this error:

```
thread 'main' panicked at src/home_assistant.rs:12:31:
Failed to read an entry: Custom { kind: Other, error: "numeric field did not have utf-8 text: �\u{f}a(��a� when getting cksum for �Yp��Uf\u{4}:&�b/� 8?\u{b}�$8?XA�YL�mK��Z�kX��}=�\u{7f}`sWT���{D\u{7}�~P�\u{14}��\u{3}5\u{1e}�DI�yp�\u{10}\u{11}\u{5}�\\���l��b�7�ט \u{1d}�G�M�Ɂ� \t�\\" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
```
my yaml :

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hass-backup-s3
  namespace: automation
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hass-backup-s3
              image: alexlikhachev/ha-backup-s3-uploader
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: hass-backup-s3-secrets
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: hass-backup-s3-secrets
                      key: aws_secret_access_key
                - name: AWS_REGION
                  value: fr-par
                - name: AWS_BUCKET
                  value: ######
                - name: AWS_ENDPOINT
                  value: https://s3.fr-par.scw.cloud
                - name: CRON_SCHEDULE
                  value: "0 0 * * *"
              volumeMounts:
                - name: home-assistant
                  mountPath: /backups
                  subPath: backups
          volumes:
            - name: home-assistant
              persistentVolumeClaim:
                claimName: automation
          restartPolicy: OnFailure
```
